# Generated by Django 3.2.9 on 2022-06-22 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebookpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userperson',
            old_name='name',
            new_name='username',
        ),
    ]
